# Generated by Django 2.2 on 2020-10-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book_Cartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBook', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
