# Generated by Django 2.2 on 2020-11-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_book_cartoon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
    ]
