# Generated by Django 2.2 on 2020-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_add_book_cartoon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book_CHILDREN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBook', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Book_FICTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBook', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Book_HISTORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBook', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload')),
            ],
        ),
    ]
